import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env.dev from project root (required - no fallbacks)
const envDevPath = path.resolve(__dirname, '../.env.dev');
if (!fs.existsSync(envDevPath)) {
  throw new Error(
    `.env.dev not found at ${envDevPath}. Run ./scripts/dc.sh to generate it.`
  );
}
dotenv.config({ path: envDevPath });

// Read required ports from environment (no fallbacks)
const FRONTEND_PORT = process.env.FRONTEND_PORT;
const BACKEND_PORT = process.env.BACKEND_PORT;

if (!FRONTEND_PORT || !BACKEND_PORT) {
  throw new Error(
    'FRONTEND_PORT and BACKEND_PORT must be set in .env.dev. Run ./scripts/dc.sh to generate it.'
  );
}

/**
 * Playwright Testing Configuration
 *
 * Three types of tests:
 * 1. UI Tests (tests/ui/*.spec.ts): Mock backend, test browser behavior & accessibility
 * 2. E2E Tests (tests/e2e/*.spec.ts): Real backend, test full system integration
 * 3. Responsive Tests (tests/responsive/*.spec.ts): Real backend, test responsive layouts
 *
 * Run UI tests:          npm run test:ui
 * Run E2E tests:         npm run test:e2e
 * Run responsive tests:  npm run test:responsive
 * Run all tests:         npm run test:all
 *
 * Port configuration: Reads from ../.env.dev file (auto-generated by ./scripts/dc.sh)
 * Each project clone gets unique ports to avoid conflicts
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  timeout: 30000,

  use: {
    baseURL: `http://localhost:${FRONTEND_PORT}`,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    // UI Tests: Mock backend, fast, test browser behavior
    {
      name: 'ui',
      testMatch: /tests\/ui\/.*\.spec\.ts/,
      use: { ...devices['Desktop Chrome'] },
    },

    // E2E Tests: Real backend, test full stack integration
    {
      name: 'e2e',
      testMatch: /tests\/e2e\/.*\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        // E2E tests need longer timeout for real backend
        timeout: 60000,
      },
    },

    // Responsive Tests: Real backend, test mobile/tablet/desktop layouts
    {
      name: 'responsive',
      testMatch: /tests\/responsive\/.*\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        // Responsive tests need longer timeout for screenshots
        timeout: 60000,
      },
    },
  ],

  webServer: {
    command: 'npm run dev',
    url: `http://localhost:${FRONTEND_PORT}`,
    reuseExistingServer: !process.env.CI,
    timeout: 120000,
  },
});
