/**
 * E2E Test Configuration
 *
 * Centralized configuration for E2E tests.
 * Reads ports from .env.dev (auto-generated by ./scripts/dc.sh).
 *
 * Usage:
 *   npm run test:e2e    # Run E2E tests using ports from .env.dev
 */

import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env.dev from project root (required - no fallbacks)
const envDevPath = path.resolve(__dirname, '../../../.env.dev');
if (!fs.existsSync(envDevPath)) {
  throw new Error(
    `.env.dev not found at ${envDevPath}. Run ./scripts/dc.sh to generate it.`
  );
}
dotenv.config({ path: envDevPath });

// Read required ports from environment (no fallbacks)
const FRONTEND_PORT = process.env.FRONTEND_PORT;
const BACKEND_PORT = process.env.BACKEND_PORT;

if (!FRONTEND_PORT || !BACKEND_PORT) {
  throw new Error(
    'FRONTEND_PORT and BACKEND_PORT must be set in .env.dev. Run ./scripts/dc.sh to generate it.'
  );
}

/**
 * Test configuration constants
 * Use these throughout E2E tests instead of hardcoded URLs
 */
export const TEST_CONFIG = {
  /** Frontend URL for navigating pages */
  FRONTEND_URL: `http://localhost:${FRONTEND_PORT}`,

  /** Backend API URL for direct API calls (used by real-backend tests) */
  BACKEND_URL: `http://localhost:${BACKEND_PORT}`,

  /** Port numbers (useful for debugging) */
  FRONTEND_PORT,
  BACKEND_PORT,
} as const;
