"""drop_live20_volume_trend

Revision ID: a0e1c5237aca
Revises: 777871ff2314
Create Date: 2026-02-10 08:58:10.265296

Trading Analyst Database Migration
This migration was auto-generated using Alembic with async SQLAlchemy support.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e1c5237aca'
down_revision: Union[str, Sequence[str], None] = '777871ff2314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function applies the migration changes to move
    the database schema forward to this revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'live20_volume_trend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function reverses the migration changes to move
    the database schema back to the previous revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('live20_volume_trend', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
