"""initial_schema

Revision ID: 4e3891cf488d
Revises: 
Create Date: 2026-01-23 10:29:28.147894

Trading Analyst Database Migration
This migration was auto-generated using Alembic with async SQLAlchemy support.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e3891cf488d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function applies the migration changes to move
    the database schema forward to this revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_simulations',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('stock_list_id', sa.Integer(), nullable=True),
    sa.Column('stock_list_name', sa.String(length=255), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=50), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('final_equity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_simulations_created_at'), 'arena_simulations', ['created_at'], unique=False)
    op.create_index(op.f('ix_arena_simulations_deleted_at'), 'arena_simulations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_arena_simulations_id'), 'arena_simulations', ['id'], unique=False)
    op.create_index(op.f('ix_arena_simulations_updated_at'), 'arena_simulations', ['updated_at'], unique=False)
    op.create_table('ib_orders',
    sa.Column('composite_order_id', sa.String(length=50), nullable=False),
    sa.Column('entry_order_id', sa.BigInteger(), nullable=False),
    sa.Column('stop_order_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'FILLED', 'CANCELLED', 'REJECTED', 'STOPPED')", name='ck_ib_orders_valid_status'),
    sa.CheckConstraint('quantity > 0', name='ck_ib_orders_positive_quantity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ib_orders_composite_order_id'), 'ib_orders', ['composite_order_id'], unique=True)
    op.create_index(op.f('ix_ib_orders_created_at'), 'ib_orders', ['created_at'], unique=False)
    op.create_index('ix_ib_orders_created_at_desc', 'ib_orders', [sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_ib_orders_deleted_at'), 'ib_orders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ib_orders_id'), 'ib_orders', ['id'], unique=False)
    op.create_index('ix_ib_orders_status', 'ib_orders', ['status'], unique=False)
    op.create_index('ix_ib_orders_symbol', 'ib_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_ib_orders_updated_at'), 'ib_orders', ['updated_at'], unique=False)
    op.create_table('live20_runs',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('long_count', sa.Integer(), nullable=False),
    sa.Column('short_count', sa.Integer(), nullable=False),
    sa.Column('no_setup_count', sa.Integer(), nullable=False),
    sa.Column('input_symbols', sa.JSON(), nullable=False),
    sa.Column('stock_list_id', sa.Integer(), nullable=True),
    sa.Column('stock_list_name', sa.String(length=255), nullable=True),
    sa.Column('source_lists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategy_config', sa.JSON(), nullable=True),
    sa.Column('worker_id', sa.String(length=50), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_symbols', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live20_runs_created_at'), 'live20_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_live20_runs_deleted_at'), 'live20_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_live20_runs_id'), 'live20_runs', ['id'], unique=False)
    op.create_index(op.f('ix_live20_runs_updated_at'), 'live20_runs', ['updated_at'], unique=False)
    op.create_table('stock_lists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbols', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_lists_created_at'), 'stock_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_lists_deleted_at'), 'stock_lists', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stock_lists_id'), 'stock_lists', ['id'], unique=False)
    op.create_index(op.f('ix_stock_lists_updated_at'), 'stock_lists', ['updated_at'], unique=False)
    op.create_index(op.f('ix_stock_lists_user_id'), 'stock_lists', ['user_id'], unique=False)
    op.create_table('stock_prices',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('price_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_change_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("data_source IN ('yahoo_finance', 'manual', 'mock', 'ib')", name='ck_stock_prices_valid_data_source'),
    sa.CheckConstraint("interval IN ('1m', '2m', '5m', '15m', '30m', '60m', '90m', '1h', '1d', '5d', '1wk', '1mo', '3mo')", name='ck_stock_prices_valid_interval'),
    sa.CheckConstraint('adjusted_close IS NULL OR adjusted_close > 0', name='ck_stock_prices_adjusted_close_positive'),
    sa.CheckConstraint('close_price > 0', name='ck_stock_prices_close_positive'),
    sa.CheckConstraint('high_price > 0', name='ck_stock_prices_high_positive'),
    sa.CheckConstraint('high_price >= close_price', name='ck_stock_prices_high_gte_close'),
    sa.CheckConstraint('high_price >= low_price', name='ck_stock_prices_high_gte_low'),
    sa.CheckConstraint('high_price >= open_price', name='ck_stock_prices_high_gte_open'),
    sa.CheckConstraint('low_price <= close_price', name='ck_stock_prices_low_lte_close'),
    sa.CheckConstraint('low_price <= open_price', name='ck_stock_prices_low_lte_open'),
    sa.CheckConstraint('low_price > 0', name='ck_stock_prices_low_positive'),
    sa.CheckConstraint('market_cap IS NULL OR market_cap > 0', name='ck_stock_prices_market_cap_positive'),
    sa.CheckConstraint('open_price > 0', name='ck_stock_prices_open_positive'),
    sa.CheckConstraint('price_change_percent IS NULL OR price_change_percent >= -100.0', name='ck_stock_prices_change_percent_valid'),
    sa.CheckConstraint('volume >= 0', name='ck_stock_prices_volume_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_created_at'), 'stock_prices', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_prices_deleted_at'), 'stock_prices', ['deleted_at'], unique=False)
    op.create_index('ix_stock_prices_freshness', 'stock_prices', ['symbol', 'interval', sa.text('last_fetched_at DESC')], unique=False)
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_index('ix_stock_prices_symbol_timestamp_desc', 'stock_prices', ['symbol', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_stock_prices_symbol_timestamp_interval', 'stock_prices', ['symbol', 'timestamp', 'interval'], unique=True)
    op.create_index(op.f('ix_stock_prices_timestamp'), 'stock_prices', ['timestamp'], unique=False)
    op.create_index('ix_stock_prices_timestamp_symbol', 'stock_prices', ['timestamp', 'symbol'], unique=False)
    op.create_index(op.f('ix_stock_prices_updated_at'), 'stock_prices', ['updated_at'], unique=False)
    op.create_table('arena_positions',
    sa.Column('simulation_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('trailing_stop_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_stop', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.Column('agent_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['arena_simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_positions_created_at'), 'arena_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_arena_positions_deleted_at'), 'arena_positions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_arena_positions_id'), 'arena_positions', ['id'], unique=False)
    op.create_index(op.f('ix_arena_positions_simulation_id'), 'arena_positions', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_arena_positions_updated_at'), 'arena_positions', ['updated_at'], unique=False)
    op.create_table('arena_snapshots',
    sa.Column('simulation_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cumulative_return_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('open_position_count', sa.Integer(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['arena_simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_snapshots_created_at'), 'arena_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_arena_snapshots_deleted_at'), 'arena_snapshots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_arena_snapshots_id'), 'arena_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_arena_snapshots_simulation_id'), 'arena_snapshots', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_arena_snapshots_updated_at'), 'arena_snapshots', ['updated_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('stock', sa.String(length=10), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('live20_trend_direction', sa.String(length=10), nullable=True),
    sa.Column('live20_trend_aligned', sa.Boolean(), nullable=True),
    sa.Column('live20_ma20_distance_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('live20_ma20_aligned', sa.Boolean(), nullable=True),
    sa.Column('live20_candle_pattern', sa.String(length=30), nullable=True),
    sa.Column('live20_candle_bullish', sa.Boolean(), nullable=True),
    sa.Column('live20_candle_aligned', sa.Boolean(), nullable=True),
    sa.Column('live20_candle_explanation', sa.String(length=255), nullable=True),
    sa.Column('live20_volume_trend', sa.String(length=15), nullable=True),
    sa.Column('live20_volume_aligned', sa.Boolean(), nullable=True),
    sa.Column('live20_volume_approach', sa.String(length=15), nullable=True),
    sa.Column('live20_cci_direction', sa.String(length=10), nullable=True),
    sa.Column('live20_cci_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('live20_cci_zone', sa.String(length=15), nullable=True),
    sa.Column('live20_cci_aligned', sa.Boolean(), nullable=True),
    sa.Column('live20_criteria_aligned', sa.Integer(), nullable=True),
    sa.Column('live20_direction', sa.String(length=10), nullable=True),
    sa.Column('live20_entry_strategy', sa.String(length=20), nullable=True),
    sa.Column('live20_exit_strategy', sa.String(length=20), nullable=True),
    sa.Column('live20_run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.CheckConstraint("recommendation IN ('Buy', 'Watchlist', 'Not Buy', 'LONG', 'SHORT', 'NO_SETUP')", name='ck_recommendations_valid_decision'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_recommendations_confidence_range'),
    sa.ForeignKeyConstraint(['live20_run_id'], ['live20_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_analysis_date'), 'recommendations', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_deleted_at'), 'recommendations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_live20_direction'), 'recommendations', ['live20_direction'], unique=False)
    op.create_index(op.f('ix_recommendations_live20_run_id'), 'recommendations', ['live20_run_id'], unique=False)
    op.create_index(op.f('ix_recommendations_source'), 'recommendations', ['source'], unique=False)
    op.create_index(op.f('ix_recommendations_stock'), 'recommendations', ['stock'], unique=False)
    op.create_index('ix_recommendations_stock_created', 'recommendations', ['stock', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_recommendations_updated_at'), 'recommendations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function reverses the migration changes to move
    the database schema back to the previous revision.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_updated_at'), table_name='recommendations')
    op.drop_index('ix_recommendations_stock_created', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_stock'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_source'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_live20_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_live20_direction'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_deleted_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_analysis_date'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_arena_snapshots_updated_at'), table_name='arena_snapshots')
    op.drop_index(op.f('ix_arena_snapshots_simulation_id'), table_name='arena_snapshots')
    op.drop_index(op.f('ix_arena_snapshots_id'), table_name='arena_snapshots')
    op.drop_index(op.f('ix_arena_snapshots_deleted_at'), table_name='arena_snapshots')
    op.drop_index(op.f('ix_arena_snapshots_created_at'), table_name='arena_snapshots')
    op.drop_table('arena_snapshots')
    op.drop_index(op.f('ix_arena_positions_updated_at'), table_name='arena_positions')
    op.drop_index(op.f('ix_arena_positions_simulation_id'), table_name='arena_positions')
    op.drop_index(op.f('ix_arena_positions_id'), table_name='arena_positions')
    op.drop_index(op.f('ix_arena_positions_deleted_at'), table_name='arena_positions')
    op.drop_index(op.f('ix_arena_positions_created_at'), table_name='arena_positions')
    op.drop_table('arena_positions')
    op.drop_index(op.f('ix_stock_prices_updated_at'), table_name='stock_prices')
    op.drop_index('ix_stock_prices_timestamp_symbol', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_timestamp'), table_name='stock_prices')
    op.drop_index('ix_stock_prices_symbol_timestamp_interval', table_name='stock_prices')
    op.drop_index('ix_stock_prices_symbol_timestamp_desc', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_index('ix_stock_prices_freshness', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_deleted_at'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_created_at'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stock_lists_user_id'), table_name='stock_lists')
    op.drop_index(op.f('ix_stock_lists_updated_at'), table_name='stock_lists')
    op.drop_index(op.f('ix_stock_lists_id'), table_name='stock_lists')
    op.drop_index(op.f('ix_stock_lists_deleted_at'), table_name='stock_lists')
    op.drop_index(op.f('ix_stock_lists_created_at'), table_name='stock_lists')
    op.drop_table('stock_lists')
    op.drop_index(op.f('ix_live20_runs_updated_at'), table_name='live20_runs')
    op.drop_index(op.f('ix_live20_runs_id'), table_name='live20_runs')
    op.drop_index(op.f('ix_live20_runs_deleted_at'), table_name='live20_runs')
    op.drop_index(op.f('ix_live20_runs_created_at'), table_name='live20_runs')
    op.drop_table('live20_runs')
    op.drop_index(op.f('ix_ib_orders_updated_at'), table_name='ib_orders')
    op.drop_index('ix_ib_orders_symbol', table_name='ib_orders')
    op.drop_index('ix_ib_orders_status', table_name='ib_orders')
    op.drop_index(op.f('ix_ib_orders_id'), table_name='ib_orders')
    op.drop_index(op.f('ix_ib_orders_deleted_at'), table_name='ib_orders')
    op.drop_index('ix_ib_orders_created_at_desc', table_name='ib_orders')
    op.drop_index(op.f('ix_ib_orders_created_at'), table_name='ib_orders')
    op.drop_index(op.f('ix_ib_orders_composite_order_id'), table_name='ib_orders')
    op.drop_table('ib_orders')
    op.drop_index(op.f('ix_arena_simulations_updated_at'), table_name='arena_simulations')
    op.drop_index(op.f('ix_arena_simulations_id'), table_name='arena_simulations')
    op.drop_index(op.f('ix_arena_simulations_deleted_at'), table_name='arena_simulations')
    op.drop_index(op.f('ix_arena_simulations_created_at'), table_name='arena_simulations')
    op.drop_table('arena_simulations')
    # ### end Alembic commands ###
